// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: docs/api/grpc/leshy_controller_v1.proto

package grpcv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RuntimeAttached bool                   `protobuf:"varint,2,opt,name=runtime_attached,json=runtimeAttached,proto3" json:"runtime_attached,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_grpc_leshy_controller_v1_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetRuntimeAttached() bool {
	if x != nil {
		return x.RuntimeAttached
	}
	return false
}

type AllowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowRequest) Reset() {
	*x = AllowRequest{}
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowRequest) ProtoMessage() {}

func (x *AllowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowRequest.ProtoReflect.Descriptor instead.
func (*AllowRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_grpc_leshy_controller_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AllowRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllowRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type AllowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowResponse) Reset() {
	*x = AllowResponse{}
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowResponse) ProtoMessage() {}

func (x *AllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowResponse.ProtoReflect.Descriptor instead.
func (*AllowResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_grpc_leshy_controller_v1_proto_rawDescGZIP(), []int{2}
}

func (x *AllowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AllowResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AllowResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllowResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type StatsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Allowed                uint64                 `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Dropped                uint64                 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	SynAllowed             uint64                 `protobuf:"varint,3,opt,name=syn_allowed,json=synAllowed,proto3" json:"syn_allowed,omitempty"`
	SynDropped             uint64                 `protobuf:"varint,4,opt,name=syn_dropped,json=synDropped,proto3" json:"syn_dropped,omitempty"`
	ActiveFlowHits         uint64                 `protobuf:"varint,5,opt,name=active_flow_hits,json=activeFlowHits,proto3" json:"active_flow_hits,omitempty"`
	PendingPromotions      uint64                 `protobuf:"varint,6,opt,name=pending_promotions,json=pendingPromotions,proto3" json:"pending_promotions,omitempty"`
	PendingExpiredCleanups uint64                 `protobuf:"varint,7,opt,name=pending_expired_cleanups,json=pendingExpiredCleanups,proto3" json:"pending_expired_cleanups,omitempty"`
	IpPortAuthHits         uint64                 `protobuf:"varint,8,opt,name=ip_port_auth_hits,json=ipPortAuthHits,proto3" json:"ip_port_auth_hits,omitempty"`
	NonGuardedPortAllowed  uint64                 `protobuf:"varint,9,opt,name=non_guarded_port_allowed,json=nonGuardedPortAllowed,proto3" json:"non_guarded_port_allowed,omitempty"`
	GuardedPortDropped     uint64                 `protobuf:"varint,10,opt,name=guarded_port_dropped,json=guardedPortDropped,proto3" json:"guarded_port_dropped,omitempty"`
	AllowRatePercent       float64                `protobuf:"fixed64,11,opt,name=allow_rate_percent,json=allowRatePercent,proto3" json:"allow_rate_percent,omitempty"`
	DropRatePercent        float64                `protobuf:"fixed64,12,opt,name=drop_rate_percent,json=dropRatePercent,proto3" json:"drop_rate_percent,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_grpc_leshy_controller_v1_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResponse) GetAllowed() uint64 {
	if x != nil {
		return x.Allowed
	}
	return 0
}

func (x *StatsResponse) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *StatsResponse) GetSynAllowed() uint64 {
	if x != nil {
		return x.SynAllowed
	}
	return 0
}

func (x *StatsResponse) GetSynDropped() uint64 {
	if x != nil {
		return x.SynDropped
	}
	return 0
}

func (x *StatsResponse) GetActiveFlowHits() uint64 {
	if x != nil {
		return x.ActiveFlowHits
	}
	return 0
}

func (x *StatsResponse) GetPendingPromotions() uint64 {
	if x != nil {
		return x.PendingPromotions
	}
	return 0
}

func (x *StatsResponse) GetPendingExpiredCleanups() uint64 {
	if x != nil {
		return x.PendingExpiredCleanups
	}
	return 0
}

func (x *StatsResponse) GetIpPortAuthHits() uint64 {
	if x != nil {
		return x.IpPortAuthHits
	}
	return 0
}

func (x *StatsResponse) GetNonGuardedPortAllowed() uint64 {
	if x != nil {
		return x.NonGuardedPortAllowed
	}
	return 0
}

func (x *StatsResponse) GetGuardedPortDropped() uint64 {
	if x != nil {
		return x.GuardedPortDropped
	}
	return 0
}

func (x *StatsResponse) GetAllowRatePercent() float64 {
	if x != nil {
		return x.AllowRatePercent
	}
	return 0
}

func (x *StatsResponse) GetDropRatePercent() float64 {
	if x != nil {
		return x.DropRatePercent
	}
	return 0
}

type UpsertManagementSettingsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Issuer             string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience           string                 `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	JwksUrl            string                 `protobuf:"bytes,3,opt,name=jwks_url,json=jwksUrl,proto3" json:"jwks_url,omitempty"`
	RequiredScope      string                 `protobuf:"bytes,4,opt,name=required_scope,json=requiredScope,proto3" json:"required_scope,omitempty"`
	GuardedPortsRange  string                 `protobuf:"bytes,5,opt,name=guarded_ports_range,json=guardedPortsRange,proto3" json:"guarded_ports_range,omitempty"`
	Iface              string                 `protobuf:"bytes,6,opt,name=iface,proto3" json:"iface,omitempty"`
	HandshakeWindowSec int32                  `protobuf:"varint,7,opt,name=handshake_window_sec,json=handshakeWindowSec,proto3" json:"handshake_window_sec,omitempty"`
	InactiveTimerSec   int32                  `protobuf:"varint,8,opt,name=inactive_timer_sec,json=inactiveTimerSec,proto3" json:"inactive_timer_sec,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpsertManagementSettingsRequest) Reset() {
	*x = UpsertManagementSettingsRequest{}
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertManagementSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertManagementSettingsRequest) ProtoMessage() {}

func (x *UpsertManagementSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertManagementSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpsertManagementSettingsRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_grpc_leshy_controller_v1_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertManagementSettingsRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *UpsertManagementSettingsRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *UpsertManagementSettingsRequest) GetJwksUrl() string {
	if x != nil {
		return x.JwksUrl
	}
	return ""
}

func (x *UpsertManagementSettingsRequest) GetRequiredScope() string {
	if x != nil {
		return x.RequiredScope
	}
	return ""
}

func (x *UpsertManagementSettingsRequest) GetGuardedPortsRange() string {
	if x != nil {
		return x.GuardedPortsRange
	}
	return ""
}

func (x *UpsertManagementSettingsRequest) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *UpsertManagementSettingsRequest) GetHandshakeWindowSec() int32 {
	if x != nil {
		return x.HandshakeWindowSec
	}
	return 0
}

func (x *UpsertManagementSettingsRequest) GetInactiveTimerSec() int32 {
	if x != nil {
		return x.InactiveTimerSec
	}
	return 0
}

type UpsertManagementSettingsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Message            string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	AuthConfigured     bool                   `protobuf:"varint,2,opt,name=auth_configured,json=authConfigured,proto3" json:"auth_configured,omitempty"`
	RuntimeAttached    bool                   `protobuf:"varint,3,opt,name=runtime_attached,json=runtimeAttached,proto3" json:"runtime_attached,omitempty"`
	RuntimeIface       string                 `protobuf:"bytes,4,opt,name=runtime_iface,json=runtimeIface,proto3" json:"runtime_iface,omitempty"`
	Issuer             string                 `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience           string                 `protobuf:"bytes,6,opt,name=audience,proto3" json:"audience,omitempty"`
	JwksUrl            string                 `protobuf:"bytes,7,opt,name=jwks_url,json=jwksUrl,proto3" json:"jwks_url,omitempty"`
	RequiredScope      string                 `protobuf:"bytes,8,opt,name=required_scope,json=requiredScope,proto3" json:"required_scope,omitempty"`
	GuardedPortsRange  string                 `protobuf:"bytes,9,opt,name=guarded_ports_range,json=guardedPortsRange,proto3" json:"guarded_ports_range,omitempty"`
	Iface              string                 `protobuf:"bytes,10,opt,name=iface,proto3" json:"iface,omitempty"`
	HandshakeWindowSec int32                  `protobuf:"varint,11,opt,name=handshake_window_sec,json=handshakeWindowSec,proto3" json:"handshake_window_sec,omitempty"`
	InactiveTimerSec   int32                  `protobuf:"varint,12,opt,name=inactive_timer_sec,json=inactiveTimerSec,proto3" json:"inactive_timer_sec,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpsertManagementSettingsResponse) Reset() {
	*x = UpsertManagementSettingsResponse{}
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertManagementSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertManagementSettingsResponse) ProtoMessage() {}

func (x *UpsertManagementSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertManagementSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpsertManagementSettingsResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_grpc_leshy_controller_v1_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertManagementSettingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertManagementSettingsResponse) GetAuthConfigured() bool {
	if x != nil {
		return x.AuthConfigured
	}
	return false
}

func (x *UpsertManagementSettingsResponse) GetRuntimeAttached() bool {
	if x != nil {
		return x.RuntimeAttached
	}
	return false
}

func (x *UpsertManagementSettingsResponse) GetRuntimeIface() string {
	if x != nil {
		return x.RuntimeIface
	}
	return ""
}

func (x *UpsertManagementSettingsResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *UpsertManagementSettingsResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *UpsertManagementSettingsResponse) GetJwksUrl() string {
	if x != nil {
		return x.JwksUrl
	}
	return ""
}

func (x *UpsertManagementSettingsResponse) GetRequiredScope() string {
	if x != nil {
		return x.RequiredScope
	}
	return ""
}

func (x *UpsertManagementSettingsResponse) GetGuardedPortsRange() string {
	if x != nil {
		return x.GuardedPortsRange
	}
	return ""
}

func (x *UpsertManagementSettingsResponse) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *UpsertManagementSettingsResponse) GetHandshakeWindowSec() int32 {
	if x != nil {
		return x.HandshakeWindowSec
	}
	return 0
}

func (x *UpsertManagementSettingsResponse) GetInactiveTimerSec() int32 {
	if x != nil {
		return x.InactiveTimerSec
	}
	return 0
}

func (x *UpsertManagementSettingsResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetManagementSettingsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AuthConfigured     bool                   `protobuf:"varint,1,opt,name=auth_configured,json=authConfigured,proto3" json:"auth_configured,omitempty"`
	RuntimeAttached    bool                   `protobuf:"varint,2,opt,name=runtime_attached,json=runtimeAttached,proto3" json:"runtime_attached,omitempty"`
	RuntimeIface       string                 `protobuf:"bytes,3,opt,name=runtime_iface,json=runtimeIface,proto3" json:"runtime_iface,omitempty"`
	Issuer             string                 `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience           string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	JwksUrl            string                 `protobuf:"bytes,6,opt,name=jwks_url,json=jwksUrl,proto3" json:"jwks_url,omitempty"`
	RequiredScope      string                 `protobuf:"bytes,7,opt,name=required_scope,json=requiredScope,proto3" json:"required_scope,omitempty"`
	GuardedPortsRange  string                 `protobuf:"bytes,8,opt,name=guarded_ports_range,json=guardedPortsRange,proto3" json:"guarded_ports_range,omitempty"`
	Iface              string                 `protobuf:"bytes,9,opt,name=iface,proto3" json:"iface,omitempty"`
	HandshakeWindowSec int32                  `protobuf:"varint,10,opt,name=handshake_window_sec,json=handshakeWindowSec,proto3" json:"handshake_window_sec,omitempty"`
	InactiveTimerSec   int32                  `protobuf:"varint,11,opt,name=inactive_timer_sec,json=inactiveTimerSec,proto3" json:"inactive_timer_sec,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetManagementSettingsResponse) Reset() {
	*x = GetManagementSettingsResponse{}
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagementSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagementSettingsResponse) ProtoMessage() {}

func (x *GetManagementSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagementSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetManagementSettingsResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_grpc_leshy_controller_v1_proto_rawDescGZIP(), []int{6}
}

func (x *GetManagementSettingsResponse) GetAuthConfigured() bool {
	if x != nil {
		return x.AuthConfigured
	}
	return false
}

func (x *GetManagementSettingsResponse) GetRuntimeAttached() bool {
	if x != nil {
		return x.RuntimeAttached
	}
	return false
}

func (x *GetManagementSettingsResponse) GetRuntimeIface() string {
	if x != nil {
		return x.RuntimeIface
	}
	return ""
}

func (x *GetManagementSettingsResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *GetManagementSettingsResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *GetManagementSettingsResponse) GetJwksUrl() string {
	if x != nil {
		return x.JwksUrl
	}
	return ""
}

func (x *GetManagementSettingsResponse) GetRequiredScope() string {
	if x != nil {
		return x.RequiredScope
	}
	return ""
}

func (x *GetManagementSettingsResponse) GetGuardedPortsRange() string {
	if x != nil {
		return x.GuardedPortsRange
	}
	return ""
}

func (x *GetManagementSettingsResponse) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *GetManagementSettingsResponse) GetHandshakeWindowSec() int32 {
	if x != nil {
		return x.HandshakeWindowSec
	}
	return 0
}

func (x *GetManagementSettingsResponse) GetInactiveTimerSec() int32 {
	if x != nil {
		return x.InactiveTimerSec
	}
	return 0
}

func (x *GetManagementSettingsResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BlockManagementResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Message               string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PendingEntriesRemoved uint64                 `protobuf:"varint,2,opt,name=pending_entries_removed,json=pendingEntriesRemoved,proto3" json:"pending_entries_removed,omitempty"`
	ActiveFlowsRemoved    uint64                 `protobuf:"varint,3,opt,name=active_flows_removed,json=activeFlowsRemoved,proto3" json:"active_flows_removed,omitempty"`
	RuntimeAttached       bool                   `protobuf:"varint,4,opt,name=runtime_attached,json=runtimeAttached,proto3" json:"runtime_attached,omitempty"`
	RuntimeIface          string                 `protobuf:"bytes,5,opt,name=runtime_iface,json=runtimeIface,proto3" json:"runtime_iface,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BlockManagementResponse) Reset() {
	*x = BlockManagementResponse{}
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockManagementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockManagementResponse) ProtoMessage() {}

func (x *BlockManagementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_grpc_leshy_controller_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockManagementResponse.ProtoReflect.Descriptor instead.
func (*BlockManagementResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_grpc_leshy_controller_v1_proto_rawDescGZIP(), []int{7}
}

func (x *BlockManagementResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlockManagementResponse) GetPendingEntriesRemoved() uint64 {
	if x != nil {
		return x.PendingEntriesRemoved
	}
	return 0
}

func (x *BlockManagementResponse) GetActiveFlowsRemoved() uint64 {
	if x != nil {
		return x.ActiveFlowsRemoved
	}
	return 0
}

func (x *BlockManagementResponse) GetRuntimeAttached() bool {
	if x != nil {
		return x.RuntimeAttached
	}
	return false
}

func (x *BlockManagementResponse) GetRuntimeIface() string {
	if x != nil {
		return x.RuntimeIface
	}
	return ""
}

var File_docs_api_grpc_leshy_controller_v1_proto protoreflect.FileDescriptor

const file_docs_api_grpc_leshy_controller_v1_proto_rawDesc = "" +
	"\n" +
	"'docs/api/grpc/leshy_controller_v1.proto\x12\x13leshy.controller.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12)\n" +
	"\x10runtime_attached\x18\x02 \x01(\bR\x0fruntimeAttached\"2\n" +
	"\fAllowRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x88\x01\n" +
	"\rAllowResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\"\x88\x04\n" +
	"\rStatsResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\x04R\aallowed\x12\x18\n" +
	"\adropped\x18\x02 \x01(\x04R\adropped\x12\x1f\n" +
	"\vsyn_allowed\x18\x03 \x01(\x04R\n" +
	"synAllowed\x12\x1f\n" +
	"\vsyn_dropped\x18\x04 \x01(\x04R\n" +
	"synDropped\x12(\n" +
	"\x10active_flow_hits\x18\x05 \x01(\x04R\x0eactiveFlowHits\x12-\n" +
	"\x12pending_promotions\x18\x06 \x01(\x04R\x11pendingPromotions\x128\n" +
	"\x18pending_expired_cleanups\x18\a \x01(\x04R\x16pendingExpiredCleanups\x12)\n" +
	"\x11ip_port_auth_hits\x18\b \x01(\x04R\x0eipPortAuthHits\x127\n" +
	"\x18non_guarded_port_allowed\x18\t \x01(\x04R\x15nonGuardedPortAllowed\x120\n" +
	"\x14guarded_port_dropped\x18\n" +
	" \x01(\x04R\x12guardedPortDropped\x12,\n" +
	"\x12allow_rate_percent\x18\v \x01(\x01R\x10allowRatePercent\x12*\n" +
	"\x11drop_rate_percent\x18\f \x01(\x01R\x0fdropRatePercent\"\xbd\x02\n" +
	"\x1fUpsertManagementSettingsRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\x12\x19\n" +
	"\bjwks_url\x18\x03 \x01(\tR\ajwksUrl\x12%\n" +
	"\x0erequired_scope\x18\x04 \x01(\tR\rrequiredScope\x12.\n" +
	"\x13guarded_ports_range\x18\x05 \x01(\tR\x11guardedPortsRange\x12\x14\n" +
	"\x05iface\x18\x06 \x01(\tR\x05iface\x120\n" +
	"\x14handshake_window_sec\x18\a \x01(\x05R\x12handshakeWindowSec\x12,\n" +
	"\x12inactive_timer_sec\x18\b \x01(\x05R\x10inactiveTimerSec\"\x8c\x04\n" +
	" UpsertManagementSettingsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12'\n" +
	"\x0fauth_configured\x18\x02 \x01(\bR\x0eauthConfigured\x12)\n" +
	"\x10runtime_attached\x18\x03 \x01(\bR\x0fruntimeAttached\x12#\n" +
	"\rruntime_iface\x18\x04 \x01(\tR\fruntimeIface\x12\x16\n" +
	"\x06issuer\x18\x05 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x06 \x01(\tR\baudience\x12\x19\n" +
	"\bjwks_url\x18\a \x01(\tR\ajwksUrl\x12%\n" +
	"\x0erequired_scope\x18\b \x01(\tR\rrequiredScope\x12.\n" +
	"\x13guarded_ports_range\x18\t \x01(\tR\x11guardedPortsRange\x12\x14\n" +
	"\x05iface\x18\n" +
	" \x01(\tR\x05iface\x120\n" +
	"\x14handshake_window_sec\x18\v \x01(\x05R\x12handshakeWindowSec\x12,\n" +
	"\x12inactive_timer_sec\x18\f \x01(\x05R\x10inactiveTimerSec\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xef\x03\n" +
	"\x1dGetManagementSettingsResponse\x12'\n" +
	"\x0fauth_configured\x18\x01 \x01(\bR\x0eauthConfigured\x12)\n" +
	"\x10runtime_attached\x18\x02 \x01(\bR\x0fruntimeAttached\x12#\n" +
	"\rruntime_iface\x18\x03 \x01(\tR\fruntimeIface\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12\x19\n" +
	"\bjwks_url\x18\x06 \x01(\tR\ajwksUrl\x12%\n" +
	"\x0erequired_scope\x18\a \x01(\tR\rrequiredScope\x12.\n" +
	"\x13guarded_ports_range\x18\b \x01(\tR\x11guardedPortsRange\x12\x14\n" +
	"\x05iface\x18\t \x01(\tR\x05iface\x120\n" +
	"\x14handshake_window_sec\x18\n" +
	" \x01(\x05R\x12handshakeWindowSec\x12,\n" +
	"\x12inactive_timer_sec\x18\v \x01(\x05R\x10inactiveTimerSec\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xed\x01\n" +
	"\x17BlockManagementResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x126\n" +
	"\x17pending_entries_removed\x18\x02 \x01(\x04R\x15pendingEntriesRemoved\x120\n" +
	"\x14active_flows_removed\x18\x03 \x01(\x04R\x12activeFlowsRemoved\x12)\n" +
	"\x10runtime_attached\x18\x04 \x01(\bR\x0fruntimeAttached\x12#\n" +
	"\rruntime_iface\x18\x05 \x01(\tR\fruntimeIface2V\n" +
	"\rHealthService\x12E\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a#.leshy.controller.v1.HealthResponse2\xa4\x01\n" +
	"\rFilterService\x12N\n" +
	"\x05Allow\x12!.leshy.controller.v1.AllowRequest\x1a\".leshy.controller.v1.AllowResponse\x12C\n" +
	"\x05Stats\x12\x16.google.protobuf.Empty\x1a\".leshy.controller.v1.StatsResponse2\xbb\x03\n" +
	"\x11ManagementService\x12}\n" +
	"\x0eCreateSettings\x124.leshy.controller.v1.UpsertManagementSettingsRequest\x1a5.leshy.controller.v1.UpsertManagementSettingsResponse\x12}\n" +
	"\x0eUpdateSettings\x124.leshy.controller.v1.UpsertManagementSettingsRequest\x1a5.leshy.controller.v1.UpsertManagementSettingsResponse\x12Y\n" +
	"\vGetSettings\x12\x16.google.protobuf.Empty\x1a2.leshy.controller.v1.GetManagementSettingsResponse\x12M\n" +
	"\x05Block\x12\x16.google.protobuf.Empty\x1a,.leshy.controller.v1.BlockManagementResponseBFZDgithub.com/devalv/leshy-controller/internal/contracts/grpc/v1;grpcv1b\x06proto3"

var (
	file_docs_api_grpc_leshy_controller_v1_proto_rawDescOnce sync.Once
	file_docs_api_grpc_leshy_controller_v1_proto_rawDescData []byte
)

func file_docs_api_grpc_leshy_controller_v1_proto_rawDescGZIP() []byte {
	file_docs_api_grpc_leshy_controller_v1_proto_rawDescOnce.Do(func() {
		file_docs_api_grpc_leshy_controller_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_api_grpc_leshy_controller_v1_proto_rawDesc), len(file_docs_api_grpc_leshy_controller_v1_proto_rawDesc)))
	})
	return file_docs_api_grpc_leshy_controller_v1_proto_rawDescData
}

var file_docs_api_grpc_leshy_controller_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_docs_api_grpc_leshy_controller_v1_proto_goTypes = []any{
	(*HealthResponse)(nil),                   // 0: leshy.controller.v1.HealthResponse
	(*AllowRequest)(nil),                     // 1: leshy.controller.v1.AllowRequest
	(*AllowResponse)(nil),                    // 2: leshy.controller.v1.AllowResponse
	(*StatsResponse)(nil),                    // 3: leshy.controller.v1.StatsResponse
	(*UpsertManagementSettingsRequest)(nil),  // 4: leshy.controller.v1.UpsertManagementSettingsRequest
	(*UpsertManagementSettingsResponse)(nil), // 5: leshy.controller.v1.UpsertManagementSettingsResponse
	(*GetManagementSettingsResponse)(nil),    // 6: leshy.controller.v1.GetManagementSettingsResponse
	(*BlockManagementResponse)(nil),          // 7: leshy.controller.v1.BlockManagementResponse
	(*timestamppb.Timestamp)(nil),            // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 9: google.protobuf.Empty
}
var file_docs_api_grpc_leshy_controller_v1_proto_depIdxs = []int32{
	8,  // 0: leshy.controller.v1.AllowResponse.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 1: leshy.controller.v1.UpsertManagementSettingsResponse.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: leshy.controller.v1.GetManagementSettingsResponse.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: leshy.controller.v1.HealthService.Health:input_type -> google.protobuf.Empty
	1,  // 4: leshy.controller.v1.FilterService.Allow:input_type -> leshy.controller.v1.AllowRequest
	9,  // 5: leshy.controller.v1.FilterService.Stats:input_type -> google.protobuf.Empty
	4,  // 6: leshy.controller.v1.ManagementService.CreateSettings:input_type -> leshy.controller.v1.UpsertManagementSettingsRequest
	4,  // 7: leshy.controller.v1.ManagementService.UpdateSettings:input_type -> leshy.controller.v1.UpsertManagementSettingsRequest
	9,  // 8: leshy.controller.v1.ManagementService.GetSettings:input_type -> google.protobuf.Empty
	9,  // 9: leshy.controller.v1.ManagementService.Block:input_type -> google.protobuf.Empty
	0,  // 10: leshy.controller.v1.HealthService.Health:output_type -> leshy.controller.v1.HealthResponse
	2,  // 11: leshy.controller.v1.FilterService.Allow:output_type -> leshy.controller.v1.AllowResponse
	3,  // 12: leshy.controller.v1.FilterService.Stats:output_type -> leshy.controller.v1.StatsResponse
	5,  // 13: leshy.controller.v1.ManagementService.CreateSettings:output_type -> leshy.controller.v1.UpsertManagementSettingsResponse
	5,  // 14: leshy.controller.v1.ManagementService.UpdateSettings:output_type -> leshy.controller.v1.UpsertManagementSettingsResponse
	6,  // 15: leshy.controller.v1.ManagementService.GetSettings:output_type -> leshy.controller.v1.GetManagementSettingsResponse
	7,  // 16: leshy.controller.v1.ManagementService.Block:output_type -> leshy.controller.v1.BlockManagementResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_docs_api_grpc_leshy_controller_v1_proto_init() }
func file_docs_api_grpc_leshy_controller_v1_proto_init() {
	if File_docs_api_grpc_leshy_controller_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_api_grpc_leshy_controller_v1_proto_rawDesc), len(file_docs_api_grpc_leshy_controller_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_docs_api_grpc_leshy_controller_v1_proto_goTypes,
		DependencyIndexes: file_docs_api_grpc_leshy_controller_v1_proto_depIdxs,
		MessageInfos:      file_docs_api_grpc_leshy_controller_v1_proto_msgTypes,
	}.Build()
	File_docs_api_grpc_leshy_controller_v1_proto = out.File
	file_docs_api_grpc_leshy_controller_v1_proto_goTypes = nil
	file_docs_api_grpc_leshy_controller_v1_proto_depIdxs = nil
}
