FROM registry.astralinux.ru/library/astra/ubi18:1.8.4 AS builder

# Установка зависимостей сборки
RUN set -e && \
    apt-get update || exit 1 && \
    apt-get install -y -q --no-install-recommends \
    make=4.3-4.1+b4 \
    clang=1:16.0-57+b1 \
    libbpf-dev=1:1.1.0-1.astra1 \
    llvm=1:16.0-57+b1 || exit 1 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /cbpf

COPY cbpf/l4_filter.c cbpf/Makefile ./

RUN make

# Сохраняем артефакты
FROM scratch
COPY --from=builder /cbpf/l4_filter.o /l4_filter.o
# Фиктивная команда, которая завершится сразу
CMD ["/dev/null"]
