FROM registry.astralinux.ru/library/astra/ubi18:1.8.4 AS builder

# Установка зависимостей сборки
RUN set -e && \
    apt-get update || exit 1 && \
    apt-get install -y -q --no-install-recommends \
    make clang libbpf-dev llvm || exit 1 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /cbpf

COPY cbpf/l4_filter.c cbpf/Makefile ./

RUN make

# Сохраняем артефакты
FROM scratch
COPY --from=builder /cbpf/l4_filter.o /l4_filter.o
# Фиктивная команда, которая завершится сразу
CMD ["/dev/null"]
