name: Trivy CBPF builder scan
on: [pull_request]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build a Docker image
        run: |
          # Собираем только builder
          docker build \
            --target builder \
            -t cbpf-builder:latest \
            -f devops/docker/cbpf/Dockerfile.astra184 .

      - name: Run Trivy vulnerability scanner on BUILDER stage
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cbpf-builder:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
