name: Trivy CBPF builder scan
on: [pull_request]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build a Docker image
        run: |
          docker build -t local-image:latest -f devops/docker/cbpf/Dockerfile.astra184 .

      - name: Run Trivy vulnerability scanner on BUILDER stage
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local-image:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '1'
          target: 'builder'
          ignore-unfixed: true
